# NewsFindr — An Agentic AI News Assistant

### Advanced GenAI for NLP  ·  By Sourojit Dhua

---

## Executive Summary

Modern readers face an imbalance between the **volume** of news produced every hour and
the **time** they have to consume it. **NewsFindr** is an **agentic AI pipeline** that
delivers *personalised, fresh, and credibility-filtered* news for any customer in a CRM.

| Stage | Agent | Responsibility |
|---|---|---|
| 1 | **LLM (Groq)** | Reasoning + summarisation engine |
| 2 | **SQL Agent** | Verify the customer's email and retrieve their interests |
| 3 | **Search Interface** | Expand queries, fetch DuckDuckGo news, filter trusted URLs |
| 4 | **Output Agent** | Retrieve final URLs and summarise each one |
| 5 | **Orchestrator** | Run end-to-end for example user queries (top-3 news + summaries) |

The notebook follows the official project rubric end to end:

1. Setting Up the LLM (low- and high-temperature)
2. SQL Agent for Data Retrieval
3. Interface Between SQL and Search Agents
4. Output from LLMs
5. Creating the Agent (Tools + ReAct)
6. Querying with the Agent
7. Conclusion

# Problem Statement

## Business Context

NewsFindr is redefining news discovery by delivering real-time news updates tailored to
user interests. Traditional search and generic feeds often cause **information overload**,
making it hard for users to access relevant, trustworthy content efficiently. NewsFindr
uses **Agentic AI** to build a news-retrieval agent that ensures accuracy and credibility
through a structured, multi-step approach - providing secure, fair, and explainable
recommendations.

## Objective

* Provide **real-time, personalised** news retrieval so users discover relevant content effortlessly.
* Ensure **accuracy and credibility** by sourcing from trusted platforms and minimising misinformation.
* Improve **engagement** through seamless discovery, reducing information overload.
* Streamline consumption by removing outdated, irrelevant content for a refined reading experience.

# 1. Setting Up the LLM

In this section we:

* **install the required libraries**,
* **load an LLM using Groq** (via `ChatGroq`),
* and **check the LLM response on a simple query**.

## 1.1 Install the required libraries

In [1]:
# Install every dependency pinned in requirements.txt (visible install step).
# Re-running is safe; already-satisfied packages are skipped.
# --disable-pip-version-check keeps the output clean (no upgrade notices).
%pip install -q --disable-pip-version-check -r requirements.txt
print("Libraries installed / verified.")

Note: you may need to restart the kernel to use updated packages.
Libraries installed / verified.

## 1.2 Imports and API key

We load the **Groq API key** from a local `.env` file so that no secret is ever
hard-coded in the notebook.

In [2]:
# Standard library
import os
import re
import json
import ast
import warnings
from urllib.parse import urlparse

# Third-party
import pandas as pd
from dotenv import load_dotenv

warnings.filterwarnings("ignore")

# Load secrets (GROQ_API_KEY) from .env
load_dotenv()
assert os.getenv("GROQ_API_KEY"), "GROQ_API_KEY is missing in .env"
print("Environment loaded.")
print("GROQ_API_KEY present:", bool(os.getenv("GROQ_API_KEY")))

Environment loaded.
GROQ_API_KEY present: True

## 1.3 Load LLMs using Groq (low and high temperature)

We use **Groq** for its very low latency on open-weight models. The model
`llama-3.1-8b-instant` follows instructions well and supports **tool-calling**, which the
agents rely on. We create **two** clients from the same model:

* **`llm`** - `temperature=0`: deterministic and auditable. This is the workhorse for every
  agentic decision (SQL, query expansion, relevance, summarisation).
* **`llm_high`** - `temperature=0.9`: creative and diverse. Used to illustrate how
  temperature changes the model's behaviour.

In [3]:
from langchain_groq import ChatGroq
from langchain_core.rate_limiters import InMemoryRateLimiter

# Name of the Groq-hosted model we will use everywhere in this notebook.
LLM_MODEL = "llama-3.1-8b-instant"

# A client-side rate limiter spreads requests out so we stay within the Groq
# free-tier tokens-per-minute budget instead of sending bursts. Both clients
# share ONE limiter so their COMBINED call rate stays within budget.
rate_limiter = InMemoryRateLimiter(
    requests_per_second=0.5,   # ~1 request every 2 seconds
    check_every_n_seconds=0.1,
    max_bucket_size=1,
)

# Low-temperature client: temperature=0 -> deterministic, reproducible behaviour.
# max_retries lets the Groq client wait out any 429 rate-limit responses.
llm = ChatGroq(
    model=LLM_MODEL,
    temperature=0,
    max_retries=10,
    rate_limiter=rate_limiter,
)

# High-temperature client: temperature=0.9 -> creative, varied behaviour.
# Used only to demonstrate the effect of temperature on the output.
llm_high = ChatGroq(
    model=LLM_MODEL,
    temperature=0.9,
    max_retries=10,
    rate_limiter=rate_limiter,
)

print("LLMs initialised via Groq.")
print("Model         :", LLM_MODEL)
print("llm temp      : 0   (deterministic)")
print("llm_high temp : 0.9 (creative)")

LLMs initialised via Groq.
Model         : llama-3.1-8b-instant
llm temp      : 0   (deterministic)
llm_high temp : 0.9 (creative)

## 1.4 Check the LLM response on a simple query

First a quick reachability check, then a side-by-side demonstration of **low vs high
temperature**.

In [4]:
# Send a simple test prompt to confirm the LLM is reachable and responding.
test_prompt = "In one sentence, what is Agentic AI?"
test_response = llm.invoke(test_prompt)

print("Prompt :", test_prompt)
print("Reply  :", test_response.content)

Prompt : In one sentence, what is Agentic AI?
Reply  : Agentic AI refers to a type of artificial intelligence that possesses autonomous decision-making capabilities, allowing it to act independently and make choices that are not explicitly programmed, often exhibiting human-like agency and self-awareness.

**Low temperature (`llm`, temperature=0) - deterministic.** A low temperature makes the
output repeatable and consistent, which is ideal for fact-based, structured, and rule-based
tasks. Asking the same question several times returns essentially the **same** answer.

In [5]:
tagline_prompt = "Give a six-word tagline for a personalised news app."
print("llm (temperature=0) - deterministic:\n")
for i in range(3):
    print(f"  {i + 1}. {llm.invoke(tagline_prompt).content.strip()}")

llm (temperature=0) - deterministic:

  1. "Stay informed, your way, every day."

  2. "Stay informed, your way, every day."

  3. "Stay informed, your way, every day."

**High temperature (`llm_high`, temperature=0.9) - creative.** A high temperature
introduces randomness and variety, which is useful for brainstorming, storytelling, and
content generation. The same prompt now yields **different** answers each time.

In [6]:
print("llm_high (temperature=0.9) - creative / varied:\n")
for i in range(3):
    print(f"  {i + 1}. {llm_high.invoke(tagline_prompt).content.strip()}")

llm_high (temperature=0.9) - creative / varied:

  1. "Stay updated with news tailored just."

  2. "Your news, anytime, anywhere, on demand."

  3. "Stay informed, your way every day."

# 2. SQL Agent for Data Retrieval

In this section we:

* **create the SQLite database** and the `customers` table with sample records
  (each record has an **email** and a list of **interests**),
* **initialize the LangChain SQL agent** to fetch data from the database,
* **initialize the system message** that constrains the agent,
* and **verify a customer's email and retrieve their details**.

## 2.1 Create the SQLite database, table and sample records

We create `customer.db`, define the `customers` table, and insert sample customers.
The inserts are **idempotent** (`INSERT OR IGNORE`) so re-running the cell never
creates duplicates.

In [7]:
import sqlite3

DB_PATH = "customer.db"

# Sample customer records: (customer_id, name, email, interests-as-JSON)
SAMPLE_CUSTOMERS = [
    ("F8641860-7", "Kevin", "kevin.f8641860-7@gmail.com", '["Politics", "Startups", "Travel"]'),
    ("203631A0-B", "Ian",   "ian.203631a0-b@gmail.com",   '["Startups", "Travel"]'),
    ("D77D96F3-3", "Julia", "julia.d77d96f3-3@gmail.com", '["India", "Automobile", "Business"]'),
    ("6EB33C45-5", "Alice", "alice.6eb33c45-5@gmail.com", '["Politics", "Technology", "Business"]'),
    ("EDD38E10-6", "Oscar", "oscar.edd38e10-6@gmail.com", '["Automobile", "India", "Sports"]'),
]

# 1. Connect (creates the SQLite database file if it does not exist).
conn = sqlite3.connect(DB_PATH)
cur = conn.cursor()

# 2. Create the customers table (email + interests are mandatory columns).
cur.execute(
    """
    CREATE TABLE IF NOT EXISTS customers (
        id            INTEGER PRIMARY KEY AUTOINCREMENT,
        customer_id   TEXT NOT NULL UNIQUE,
        name          TEXT NOT NULL,
        email         TEXT NOT NULL UNIQUE,
        interests     TEXT NOT NULL,
        last_updated  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """
)

# 3. Insert the sample records (INSERT OR IGNORE -> no duplicates on re-run).
cur.executemany(
    "INSERT OR IGNORE INTO customers (customer_id, name, email, interests) "
    "VALUES (?, ?, ?, ?)",
    SAMPLE_CUSTOMERS,
)
conn.commit()

# 4. Show the table contents as a readable DataFrame.
customers_df = pd.read_sql_query(
    "SELECT id, customer_id, name, email, interests FROM customers ORDER BY id", conn
)
conn.close()

print("SQLite database ready at:", DB_PATH)
print("Total customers:", len(customers_df))
customers_df.head(10)

SQLite database ready at: customer.db
Total customers: 15

,id,customer_id,name,email,interests
0,1,F8641860-7,Kevin,kevin.f8641860-7@gmail.com,"[""Politics"", ""Startups"", ""Travel""]"
1,2,203631A0-B,Ian,ian.203631a0-b@gmail.com,"[""Startups"", ""Travel""]"
2,3,D77D96F3-3,Julia,julia.d77d96f3-3@gmail.com,"[""India"", ""Automobile"", ""Business""]"
3,4,6EB33C45-5,Alice,alice.6eb33c45-5@gmail.com,"[""Politics"", ""Technology"", ""Business""]"
4,5,EDD38E10-6,Oscar,oscar.edd38e10-6@gmail.com,"[""Automobile"", ""India"", ""Sports""]"
5,6,4770B814-2,Hannah,hannah.4770b814-2@gmail.com,"[""Entertainment"", ""Business"", ""Technology""]"
6,7,5483CB53-8,George,george.5483cb53-8@gmail.com,"[""India"", ""Politics"", ""Science""]"
7,8,FA8FE05B-7,Lily,lily.fa8fe05b-7@gmail.com,"[""India"", ""Science""]"
8,9,C63FA237-E,Nora,nora.c63fa237-e@gmail.com,"[""Entertainment"", ""Business""]"
9,10,45E01919-0,Lily,lily.45e01919-0@gmail.com,"[""India"", ""India"", ""Politics""]"

## 2.2 Connect LangChain to the database

We wrap the SQLite file in LangChain's `SQLDatabase` utility, which exposes the schema
and a safe `run()` method the SQL agent and our helpers use.

In [8]:
from langchain_community.utilities import SQLDatabase

DB_URI = "sqlite:///customer.db"
db = SQLDatabase.from_uri(DB_URI)

print("Dialect       :", db.dialect)
print("Usable tables :", db.get_usable_table_names())
print()
print("Schema preview:")
print(db.get_table_info(["customers"]))

Dialect       : sqlite
Usable tables : ['customers']

Schema preview:

CREATE TABLE customers (
	id INTEGER,
	customer_id TEXT NOT NULL,
	name TEXT NOT NULL,
	email TEXT NOT NULL,
	interests TEXT NOT NULL,
	last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id),
	UNIQUE (customer_id),
	UNIQUE (email)
)

/*
3 rows from customers table:
id	customer_id	name	email	interests	last_updated
1	F8641860-7	Kevin	kevin.f8641860-7@gmail.com	["Politics", "Startups", "Travel"]	2025-03-26 06:46:15
2	203631A0-B	Ian	ian.203631a0-b@gmail.com	["Startups", "Travel"]	2025-03-26 06:46:15
3	D77D96F3-3	Julia	julia.d77d96f3-3@gmail.com	["India", "Automobile", "Business"]	2025-03-26 06:46:15
*/

## 2.3 Initialize the SQL agent and the system message

We initialize a **LangChain SQL agent** with `create_sql_agent`. The **system message**
(`SQL_SYSTEM_MESSAGE`, passed as the agent `prefix`) constrains the agent to safe,
read-only `SELECT` queries against the `customers` table.

In [9]:
from langchain_community.agent_toolkits.sql.base import create_sql_agent

# ---- System message: the operating instructions for the SQL agent ----------
SQL_SYSTEM_MESSAGE = (
    "You are NewsFindr's SQL agent for a customer CRM database.\n"
    "You have access to a SQLite table called `customers` with columns: "
    "id, customer_id, name, email, interests, last_updated.\n"
    "Rules:\n"
    "1. Only ever issue read-only SELECT statements. Never INSERT/UPDATE/DELETE/DROP.\n"
    "2. When verifying a customer by email, match case-insensitively using "
    "LOWER(email) = LOWER('<value>').\n"
    "3. Return the customer's name, email and interests when asked to verify them.\n"
    "4. If no customer matches, clearly state that the customer was not found."
)

# ---- Initialize the SQL agent -----------------------------------------------
sql_agent = create_sql_agent(
    llm=llm,
    db=db,
    agent_type="zero-shot-react-description",
    prefix=SQL_SYSTEM_MESSAGE,
    verbose=True,
    handle_parsing_errors=True,
    max_iterations=10,
)

print("SQL agent initialized with a custom system message.")

SQL agent initialized with a custom system message.

## 2.4 Verify the customer's email and retrieve their details

**(a) Using the LangChain SQL agent** — we ask the agent (in natural language) to verify
an email and return the customer's details. The agent's reasoning is shown above its
final answer.

In [10]:
# Run the SQL agent to verify an email and retrieve the customer's details.
agent_question = (
    "Verify whether the email 'kevin.f8641860-7@gmail.com' belongs to a customer. "
    "If it does, return their name, email and interests."
)
try:
    agent_response = sql_agent.invoke({"input": agent_question})
    print("\n=== SQL AGENT FINAL ANSWER ===")
    print(agent_response["output"])
except Exception as exc:
    print("SQL agent error:", exc)

> Entering new SQL Agent Executor chain...

Action: sql_db_list_tables
Action Input: customers

Question: Verify whether the email 'kevin.f8641860-7@gmail.com' belongs to a customer. If it does, return their name, email and interests.
Thought: I should query the schema of the customers table to see what columns it has.
Action: sql_db_schema
Action Input: customers
CREATE TABLE customers (
	id INTEGER,
	customer_id TEXT NOT NULL,
	name TEXT NOT NULL,
	email TEXT NOT NULL,
	interests TEXT NOT NULL,
	last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id),
	UNIQUE (customer_id),
	UNIQUE (email)
)

/*
3 rows from customers table:
id	customer_id	name	email	interests	last_updated
1	F8641860-7	Kevin	kevin.f8641860-7@gmail.com	["Politics", "Startups", "Travel"]	2025-03-26 06:46:15
2	203631A0-B	Ian	ian.203631a0-b@gmail.com	["Startups", "Travel"]	2025-03-26 06:46:15
3	D77D96F3-3	Julia	julia.d77d96f3-3@gmail.com	["India", "Automobile", "Business"]	2025-03-26 06:46:15
*/

Question: Verify whether the email 'kevin.f8641860-7@gmail.com' belongs to a customer. If it does, return their name, email and interests.
Thought: I should use a SELECT query to find the customer with the matching email. I should use the LOWER() function to match the email case-insensitively.
Action: sql_db_query_checker
Action Input: SELECT name, email, interests FROM customers WHERE LOWER(email) = LOWER('kevin.f8641860-7@gmail.com')

SELECT name, email, interests FROM customers WHERE LOWER(email) = LOWER('kevin.f8641860-7@gmail.com')

Question: Verify whether the email 'kevin.f8641860-7@gmail.com' belongs to a customer. If it does, return their name, email and interests.
Thought: I should use a SELECT query to find the customer with the matching email. I should use the LOWER() function to match the email case-insensitively.
Action: sql_db_query
Action Input: SELECT name, email, interests FROM customers WHERE LOWER(email) = LOWER('kevin.f8641860-7@gmail.com')[('Kevin', 'kevin.f8641860-7@gmail.com', '["Politics", "Startups", "Travel"]')]

Question: Verify whether the email 'kevin.f8641860-7@gmail.com' belongs to a customer. If it does, return their name, email and interests.
Thought: I should look at the tables in the database to see what I can query.  Then I should query the schema of the most relevant tables.
Action: sql_db_list_tables
Action Input: customers

Question: Verify whether the email 'kevin.f8641860-7@gmail.com' belongs to a customer. If it does, return their name, email and interests.
Thought: I should look at the tables in the database to see what I can query.  Then I should query the schema of the most relevant tables.
Action: sql_db_list_tables
Action Input: customers

Question: Verify whether the email 'kevin.f8641860-7@gmail.com' belongs to a customer. If it does, return their name, email and interests.
Thought: I should look at the tables in the database to see what I can query.  Then I should query the schema of the most relevant tables.
Action: sql_db_list_tables
Action Input: customers

Question: Verify whether the email 'kevin.f8641860-7@gmail.com' belongs to a customer. If it does, return their name, email and interests.
Thought: I should look at the tables in the database to see what I can query.  Then I should query the schema of the most relevant tables.
Action: sql_db_list_tables
Action Input: customers

Question: Verify whether the email 'kevin.f8641860-7@gmail.com' belongs to a customer. If it does, return their name, email and interests.
Thought: I should look at the tables in the database to see what I can query.  Then I should query the schema of the most relevant tables.
Action: sql_db_list_tables
Action Input: customers

Question: Verify whether the email 'kevin.f8641860-7@gmail.com' belongs to a customer. If it does, return their name, email and interests.
Thought: I should look at the tables in the database to see what I can query.  Then I should query the schema of the most relevant tables.
Action: sql_db_list_tables
Action Input: customers

> Finished chain.

=== SQL AGENT FINAL ANSWER ===
Agent stopped due to iteration limit or time limit.

**(b) A deterministic helper for the pipeline.** Agents can be verbose, so for the
downstream pipeline we also expose `get_customer_by_email()`. It uses the LLM to write a
single safe `SELECT`, runs it via `db.run()`, and returns a clean Python dictionary.
This keeps the orchestrator fast and 100% reproducible.

In [11]:
from langchain_core.prompts import ChatPromptTemplate

# Prompt that turns a request into ONE safe SELECT statement.
SQL_QUERY_PROMPT = ChatPromptTemplate.from_messages(
    [
        ("system", SQL_SYSTEM_MESSAGE +
         "\nAlways use SELECT * to return ALL columns. "
         "Output ONLY the raw SQL SELECT query - no markdown, no commentary."),
        ("human", "Request: {request}\nSchema:\n{schema}"),
    ]
)
sql_query_chain = SQL_QUERY_PROMPT | llm


def get_customer_by_email(email: str) -> dict:
    """Verify the email via SQL and return the customer profile as a dict."""
    schema = db.get_table_info(["customers"])
    request = f"Find the customer whose email is '{email}'. Return ONLY a SELECT query."

    # 1. Ask the LLM to write the SELECT query.
    raw_query = sql_query_chain.invoke({"request": request, "schema": schema}).content
    raw_query = raw_query.replace("```sql", "").replace("```", "").strip()

    # 2. Guardrail: only allow SELECT statements.
    if not raw_query.upper().startswith("SELECT"):
        return {"error": "NOT_FOUND", "email": email}

    # 3. Execute the query safely.
    try:
        result = db.run(raw_query)
    except Exception:
        return {"error": "NOT_FOUND", "email": email}
    if not result or str(result).strip() in ("", "None", "[]"):
        return {"error": "NOT_FOUND", "email": email}

    # 4. Parse the first row into a clean dictionary.
    try:
        rows = ast.literal_eval(result)
    except Exception:
        return {"error": "NOT_FOUND", "email": email}
    if not rows:
        return {"error": "NOT_FOUND", "email": email}

    # Parse the row robustly, regardless of which/how many columns were selected.
    row = list(rows[0])

    # email -> the value containing '@'
    email_idx = next((i for i, x in enumerate(row) if isinstance(x, str) and "@" in x), None)
    email_val = str(row[email_idx]) if email_idx is not None else email

    # interests -> the value that is (or looks like) a JSON list
    interests = []
    for x in row:
        if isinstance(x, list):
            interests = x
            break
        if isinstance(x, str) and x.strip().startswith("["):
            try:
                interests = json.loads(x)
                break
            except Exception:
                pass

    # name -> for SELECT * the name column sits immediately before the email column.
    name_val = ""
    if email_idx is not None and email_idx > 0 and isinstance(row[email_idx - 1], str):
        name_val = str(row[email_idx - 1])

    # Deduplicate interests while keeping order.
    interests = list(dict.fromkeys(interests))

    return {
        "name": name_val,
        "email": email_val,
        "interests": interests,
    }


# Verify a real customer and store the profile for later demos.
demo_profile = get_customer_by_email("kevin.f8641860-7@gmail.com")
print("Verified customer profile (deterministic helper):")
print(json.dumps(demo_profile, indent=2))

Verified customer profile (deterministic helper):
{
  "name": "Kevin",
  "email": "kevin.f8641860-7@gmail.com",
  "interests": [
    "Politics",
    "Startups",
    "Travel"
  ]
}

**Negative test** — an email that is *not* in the database is correctly rejected.

In [12]:
missing = get_customer_by_email("not.a.real.user@example.com")
print("Lookup for an unknown email:", missing)

Lookup for an unknown email: {'error': 'NOT_FOUND', 'email': 'not.a.real.user@example.com'}

# 3. Interface Between SQL and Search Agents

Once the SQL agent hands us a verified customer profile, the **Search Agent** takes over
in three explicit steps:

1. **Create an expanded search query** — turn each raw interest into a precise query that
   targets the *latest* credible news.
2. **Fetch the news results using DuckDuckGo**.
3. **Filter relevant and trustworthy news URLs** based on the user's interests.

## 3.1 Create an expanded search query

For each interest we ask the LLM to write **one** focused web-search query aimed at the
latest, credible news on that topic.

In [13]:
# Prompt that expands a single interest into a precise news search query.
# An optional free-text user_query lets the customer steer the focus (e.g. "elections").
QUERY_EXPANSION_PROMPT = ChatPromptTemplate.from_messages(
    [
        ("system",
         "You are a senior news editor. Given a single topic of interest (and an optional "
         "user request), write ONE concise web search query (max 12 words) that surfaces "
         "the LATEST, credible news on that topic. If a user request is given, bias the "
         "query toward it. Output ONLY the query string - no quotes, no commentary."),
        ("human", "Topic: {interest}\nUser request (optional): {user_query}"),
    ]
)
query_expansion_chain = QUERY_EXPANSION_PROMPT | llm


def expand_queries(interests: list, user_query: str = "") -> dict:
    """Return {interest: expanded_search_query} for every interest.

    The optional ``user_query`` biases each generated query toward a specific need.
    """
    expanded = {}
    for interest in interests:
        q = query_expansion_chain.invoke(
            {"interest": interest, "user_query": user_query}
        ).content
        expanded[interest] = q.strip().strip('"')
    return expanded


# Demo: expand the verified customer's interests (no user query yet).
example_queries = expand_queries(demo_profile["interests"])
print("Expanded search queries for", demo_profile["name"], ":\n")
for interest, q in example_queries.items():
    print(f"  {interest:<10} ->  {q}")

Expanded search queries for Kevin :

  Politics   ->  US Politics News Latest Developments and Updates Today
  Startups   ->  Latest startup funding trends and investments in 2024
  Travel     ->  Travel industry trends and updates for 2024 summer season

## 3.2 Fetch the news results using DuckDuckGo

We query DuckDuckGo for each expanded query. `timelimit="w"` restricts results to the
**past week**, enforcing freshness. Each result is normalised to
`{title, link, snippet}`.

In [14]:
# DDGS is provided by the duckduckgo_search library (newer releases expose it as `ddgs`).
try:
    from ddgs import DDGS
except ImportError:
    from duckduckgo_search import DDGS


def search_web(query: str, max_results: int = 15, timelimit: str = "w") -> list:
    """Return DuckDuckGo news/text results as a list of {title, link, snippet}.

    ``timelimit`` restricts freshness: "w" = past week (default), "m" = past month.
    The month window is used as a fallback when a week yields too few trusted hits.
    """
    try:
        with DDGS() as ddgs:
            raw = list(ddgs.text(query, max_results=max_results, timelimit=timelimit))
    except Exception as exc:
        print(f"  [warn] DuckDuckGo failed for '{query}': {exc}")
        return []

    results = []
    for r in raw:
        results.append({
            "title": r.get("title") or "",
            "link": r.get("href") or r.get("link") or "",
            "snippet": r.get("body") or r.get("snippet") or "",
        })
    # Keep only results that actually have a URL.
    return [r for r in results if r["link"]]


# Demo: fetch results for EVERY expanded query and pool them together. Tagging each
# hit with its interest lets the later trust/relevance steps work on a rich candidate set.
demo_hits = []
for interest, q in example_queries.items():
    hits = search_web(q, max_results=12)
    for h in hits:
        h["interest"] = interest
    demo_hits.extend(hits)

print(f"Retrieved {len(demo_hits)} URLs across {len(example_queries)} queries.\n")
for hit in demo_hits[:15]:
    print(f"- [{hit['interest']}] {hit['title'][:70]}")
    print(f"    {hit['link']}")

Retrieved 36 URLs across 3 queries.

- [Politics] WATCH: House rejects short-term FISA extension | PBS News
    https://www.pbs.org/newshour/politics/watch-live-house-expected-to-vote-on-short-term-fisa-extension
- [Politics] Is Trump about to ruin the World Cup? | Politics Weekly America
    https://www.theguardian.com/politics/video/2026/jun/11/is-trump-about-to-ruin-the-world-cup-politics-weekly-america-
- [Politics] Trump Makes New Threats After U.S. and Iran Exchange Fresh Strikes
    https://www.nytimes.com/video/world/middleeast/100000010960555/trump-makes-new-threats-after-us-and-iran-exchange-fresh-strikes.html
- [Politics] U.S. Forces Complete Latest Strikes in Iran - centcom
    https://www.centcom.mil/MEDIA/PUBLIC-RELEASES/Article/4514154/us-forces-complete-latest-strikes-in-iran/
- [Politics] U.S. Politics - The New York Times
    https://www.nytimes.com/section/politics
- [Politics] Latest US politics news, comment and analysis from the Guardian...
    https://www.theguardian.com/us-news/us-politics
- [Politics] MS NOW - Breaking News and News Today | Latest News
    https://www.ms.now/
- [Politics] Politics - Bloomberg
    https://www.bloomberg.com/politics
- [Politics] Politics | Latest News & Updates | BBC News
    https://www.bbc.com/news/politics
- [Politics] Politics News: Political parties, election news, policies, and news...
    https://www.cbsnews.com/politics/
- [Politics] Breaking News, Latest News and Videos | CNN
    https://edition.cnn.com/
- [Politics] Axios - Breaking news, U.S. news and politics, and local news
    https://www.axios.com/
- [Startups] Stay Ahead of the Curve with Startup Funding News 2024
    https://ipledg.com/blog/discover-the-latest-startup-funding-trends-and-investment-opportunities-in-2024
- [Startups] Get Ahead of the Game: Predicting Startup Funding Trends in 2025
    https://ipledg.com/blog/unlock-the-secrets-to-maximize-startup-funding-in-2025-with-our-predictions-and-strategies
- [Startups] 2024 Startup Funding Research: Discover the Latest Trends and
    https://ipledg.com/blog/research-on-startup-funding-in-2024

## 3.3 Filter relevant and trustworthy news URLs — trusted-domain allowlist

First we keep only URLs from a **curated allowlist of reputable publishers** (Reuters,
BBC, CNN, TechCrunch, Forbes, and many more). Untrusted domains are dropped before the
LLM ever sees them.

In [15]:
# Curated allowlist of reputable publishers (extend as needed for new markets).
TRUSTED_DOMAINS = {
    # Global wire services & majors
    "reuters.com", "apnews.com", "bbc.com", "bbc.co.uk", "cnn.com", "edition.cnn.com",
    "nytimes.com", "wsj.com", "ft.com", "theguardian.com", "bloomberg.com", "cnbc.com",
    "economist.com", "aljazeera.com", "npr.org", "washingtonpost.com",
    # Business
    "forbes.com", "fortune.com", "businessinsider.com",
    # India
    "thehindu.com", "indianexpress.com", "livemint.com", "ndtv.com",
    "hindustantimes.com", "business-standard.com", "moneycontrol.com",
    "economictimes.indiatimes.com", "indiatoday.in",
    # Technology / startups
    "techcrunch.com", "theverge.com", "wired.com", "arstechnica.com",
    "engadget.com", "venturebeat.com",
    # Sports
    "espn.com", "espncricinfo.com", "skysports.com",
    # Automobile
    "autocarindia.com", "caranddriver.com", "motortrend.com", "autocar.co.uk",
    # Travel
    "lonelyplanet.com", "cntraveler.com", "travelandleisure.com", "nationalgeographic.com",
    # Science
    "nasa.gov", "who.int", "nature.com", "sciencemag.org",
}


def domain_of(url: str) -> str:
    """Return the bare domain (without leading www.) for a URL."""
    try:
        host = urlparse(url).netloc.lower()
        return host[4:] if host.startswith("www.") else host
    except Exception:
        return ""


def filter_trusted(hits: list) -> list:
    """Keep only hits whose domain (or parent domain) is on the allowlist."""
    kept = []
    for h in hits:
        d = domain_of(h["link"])
        if not d:
            continue
        if any(d == td or d.endswith("." + td) for td in TRUSTED_DOMAINS):
            kept.append({**h, "domain": d})
    return kept


# Demo: apply the trust filter to the raw hits.
trusted_demo = filter_trusted(demo_hits)
print(f"Kept {len(trusted_demo)} of {len(demo_hits)} URLs after trusted-domain filtering:\n")
for t in trusted_demo:
    print(f"- [{t['domain']}] {t['title'][:70]}")
    print(f"    {t['link']}")

Kept 9 of 36 URLs after trusted-domain filtering:

- [theguardian.com] Is Trump about to ruin the World Cup? | Politics Weekly America
    https://www.theguardian.com/politics/video/2026/jun/11/is-trump-about-to-ruin-the-world-cup-politics-weekly-america-
- [nytimes.com] Trump Makes New Threats After U.S. and Iran Exchange Fresh Strikes
    https://www.nytimes.com/video/world/middleeast/100000010960555/trump-makes-new-threats-after-us-and-iran-exchange-fresh-strikes.html
- [nytimes.com] U.S. Politics - The New York Times
    https://www.nytimes.com/section/politics
- [theguardian.com] Latest US politics news, comment and analysis from the Guardian...
    https://www.theguardian.com/us-news/us-politics
- [bloomberg.com] Politics - Bloomberg
    https://www.bloomberg.com/politics
- [bbc.com] Politics | Latest News & Updates | BBC News
    https://www.bbc.com/news/politics
- [edition.cnn.com] Breaking News, Latest News and Videos | CNN
    https://edition.cnn.com/
- [economictimes.indiatimes.com] Startup funding: PE, VC funding slows in first half of 2024; secondary
    https://economictimes.indiatimes.com/tech/funding/pe-vc-funding-slows-in-first-half-of-2024-secondary-deals-become-prominent/articleshow/111495240.cms
- [bbc.com] The seven travel trends that will shape 2025
    https://www.bbc.com/travel/article/20250106-the-seven-travel-trends-that-will-shape-2025

## 3.4 Filter relevant news URLs — LLM relevance judge

Among the trusted URLs, we ask the LLM to keep only those genuinely **relevant** to the
customer's interests, ordered best-first.

In [16]:
# Prompt that selects the most relevant article indices.
RELEVANCE_PROMPT = ChatPromptTemplate.from_messages(
    [
        ("system",
         "You are a news relevance judge. Given a customer's interests, an optional user "
         "request, and a numbered list of candidate articles, return ONLY a JSON array of "
         "the zero-based indices of the articles that are genuinely about one of the "
         "interests (or the user request) AND look like substantive news. Return at most "
         "{top_k} indices, ordered best-first. Example output: [0, 2, 5]"),
        ("human",
         "Customer interests: {interests}\nUser request (optional): {user_query}\n\n"
         "Candidates:\n{candidates}"),
    ]
)
relevance_chain = RELEVANCE_PROMPT | llm


def llm_select_relevant(hits: list, interests: list, top_k: int = 5,
                        user_query: str = "") -> list:
    """Use the LLM to pick the most relevant hits for the interests + user query."""
    if not hits:
        return []

    candidates_text = "\n".join(
        f"{i}. [{h.get('domain', '')}] {h['title']} - {h['snippet'][:160]}"
        for i, h in enumerate(hits)
    )
    raw = relevance_chain.invoke({
        "interests": ", ".join(interests),
        "user_query": user_query,
        "candidates": candidates_text,
        "top_k": top_k,
    }).content.strip()

    # Parse the JSON array of indices from the model output.
    selected = []
    m = re.search(r"\[[^\]]*\]", raw)
    if m:
        try:
            parsed = json.loads(m.group(0))
            selected = [i for i in parsed if isinstance(i, int) and 0 <= i < len(hits)]
        except json.JSONDecodeError:
            selected = []

    # Pad with remaining hits if the LLM returned fewer than top_k.
    remaining = [i for i in range(len(hits)) if i not in selected]
    selected.extend(remaining[: top_k - len(selected)])
    return [hits[i] for i in selected][:top_k]


# Demo: pick the relevant trusted hits for the customer.
relevant_demo = llm_select_relevant(trusted_demo, demo_profile["interests"], top_k=5)
print(f"LLM kept {len(relevant_demo)} relevant URLs:\n")
for r in relevant_demo:
    print(f"- [{r['domain']}] {r['title'][:70]}")
    print(f"    {r['link']}")

LLM kept 5 relevant URLs:

- [theguardian.com] Is Trump about to ruin the World Cup? | Politics Weekly America
    https://www.theguardian.com/politics/video/2026/jun/11/is-trump-about-to-ruin-the-world-cup-politics-weekly-america-
- [nytimes.com] Trump Makes New Threats After U.S. and Iran Exchange Fresh Strikes
    https://www.nytimes.com/video/world/middleeast/100000010960555/trump-makes-new-threats-after-us-and-iran-exchange-fresh-strikes.html
- [nytimes.com] U.S. Politics - The New York Times
    https://www.nytimes.com/section/politics
- [theguardian.com] Latest US politics news, comment and analysis from the Guardian...
    https://www.theguardian.com/us-news/us-politics
- [bloomberg.com] Politics - Bloomberg
    https://www.bloomberg.com/politics

# 4. Output from LLMs

In this section we use the LLM to:

* **retrieve the final URLs** for the latest news based on customer interest, and
* **create a summary of each retrieved link**.

For every URL we attempt a lightweight content fetch (with a graceful fallback to the
search snippet) and then ask the LLM for a clean 3-4 sentence summary framed for the
customer's interests.

## 4.1 Fetch article text and summarise each URL

In [17]:
import requests
from bs4 import BeautifulSoup

HEADERS = {
    "User-Agent": "Mozilla/5.0 (compatible; NewsFindrBot/1.0; +https://newsfindr.local)"
}


def fetch_article_text(url: str, max_chars: int = 1500, timeout: int = 8) -> str:
    """Best-effort article extraction. Returns '' on any failure."""
    try:
        resp = requests.get(url, headers=HEADERS, timeout=timeout)
        if resp.status_code != 200 or not resp.text:
            return ""
        soup = BeautifulSoup(resp.text, "html.parser")
        for tag in soup(["script", "style", "nav", "footer", "header", "aside"]):
            tag.decompose()
        paragraphs = [p.get_text(" ", strip=True) for p in soup.find_all("p")]
        return "\n".join(p for p in paragraphs if len(p) > 40)[:max_chars]
    except Exception:
        return ""


# Prompt for a clean, preamble-free summary.
SUMMARY_PROMPT = ChatPromptTemplate.from_messages(
    [
        ("system",
         "You are an expert news editor writing for a single subscriber. You are ALWAYS "
         "given enough context (a title, a snippet and possibly article text). Write a "
         "tight 3-4 sentence summary and explicitly state why it matters for a reader "
         "interested in: {interests}. Start DIRECTLY with the summary - do NOT write any "
         "preamble such as 'Here is a summary'. NEVER refuse or ask for more content. "
         "Be factual and do not invent details."),
        ("human", "Title: {title}\nSource: {domain}\nURL: {url}\n\nContent:\n{content}"),
    ]
)
summary_chain = SUMMARY_PROMPT | llm


def clean_summary(text: str) -> str:
    """Strip any leading 'Here is a summary...' style preamble lines."""
    lines = text.strip().split("\n")
    while lines and re.match(
        r"^\s*(here\s+(is|are)\b|sure[,!]|below is|here's)\b.*",
        lines[0], re.IGNORECASE,
    ):
        lines.pop(0)
    return "\n".join(lines).strip()


def summarise(hit: dict, interests: list, user_query: str = "") -> str:
    """Fetch the article (fallback to snippet/title) and summarise it cleanly.

    ``user_query`` is folded into the framing so the summary speaks to the specific need.
    """
    body = fetch_article_text(hit["link"])
    # Always guarantee non-empty context so the model never refuses.
    content = (body + "\n" + hit.get("snippet", "")).strip()
    if not content:
        content = hit.get("title", "")

    framing = ", ".join(interests)
    if user_query:
        framing += f"; with specific focus on: {user_query}"

    raw = summary_chain.invoke({
        "title": hit.get("title", ""),
        "domain": hit.get("domain", domain_of(hit["link"])),
        "url": hit["link"],
        "content": content,
        "interests": framing,
    }).content
    return clean_summary(raw)


# Demo: summarise the top relevant hit.
if relevant_demo:
    sample = relevant_demo[0]
    print("Final URL :", sample["link"])
    print("Source    :", sample["domain"])
    print("\nSummary:\n")
    print(summarise(sample, demo_profile["interests"]))

Final URL : https://www.theguardian.com/politics/video/2026/jun/11/is-trump-about-to-ruin-the-world-cup-politics-weekly-america-
Source    : theguardian.com

Summary:

Donald Trump is using high-profile sporting events to promote himself, raising concerns about his influence on football, UFC, and basketball. This matters for Politics readers as it highlights Trump's continued use of public platforms for personal gain, potentially blurring the lines between politics and sports. For Startups, this story showcases the intersection of celebrity influence and brand promotion, a key area of interest for entrepreneurs and marketers. Travel enthusiasts may be interested in the World Cup aspect, which could be impacted by Trump's involvement.

## 4.2 End-to-end pipeline

`newsfindr()` chains every component into one auditable call:

```
email -> SQL agent -> query expansion -> DuckDuckGo search -> trusted-domain filter
      -> LLM relevance filter -> per-URL summarisation -> TOP-3 result
```

It now also accepts an optional free-text **`user_query`** that is threaded through query
expansion, relevance ranking, and summarisation. `render()` prints the verified profile,
the **top-3 URLs**, a readable **DataFrame**, and a clearly separated **summary for each**
result. `query_response(email, user_query)` is a thin convenience wrapper that runs the
pipeline and renders the digest in one call.

In [18]:
def dedupe_by_url(hits: list) -> list:
    """Drop exact-duplicate URLs while preserving order."""
    seen, kept = set(), []
    for h in hits:
        u = h["link"]
        if u in seen:
            continue
        seen.add(u)
        kept.append(h)
    return kept


def dedupe_by_domain(hits: list) -> list:
    """Keep only the first hit from each domain to diversify sources."""
    seen, kept = set(), []
    for h in hits:
        d = h.get("domain") or domain_of(h["link"])
        if d in seen:
            continue
        seen.add(d)
        kept.append(h)
    return kept


def diversify(hits: list, min_keep: int) -> list:
    """Prefer one article per domain for source diversity, but never drop below
    ``min_keep`` candidates: if one-per-domain is too few, top up with the
    remaining (same-domain) articles so the top-N can always be filled."""
    primary = dedupe_by_domain(hits)
    if len(primary) >= min_keep:
        return primary
    chosen = {h["link"] for h in primary}
    for h in hits:
        if h["link"] not in chosen:
            primary.append(h)
            chosen.add(h["link"])
    return primary


def newsfindr(email: str, user_query: str = "", top_n: int = 3,
              verbose: bool = True) -> dict:
    """Full agentic pipeline. Returns the customer profile and top-N news items.

    ``user_query`` is an optional free-text need (e.g. "elections this week") that steers
    query expansion, relevance ranking and summarisation on top of the stored interests.
    """
    # Step 1 - verify customer + retrieve interests (SQL agent).
    profile = get_customer_by_email(email)
    if profile.get("error") == "NOT_FOUND":
        return {"error": "NOT_FOUND", "email": email}
    interests = profile["interests"]

    if verbose:
        print(f"Customer  : {profile['name']} <{profile['email']}>")
        print(f"Interests : {interests}")
        if user_query:
            print(f"User query: {user_query}")
        print()

    # Step 2 - expand each interest into a precise search query (biased by user_query).
    queries = expand_queries(interests, user_query=user_query)
    if verbose:
        print("Expanded search queries:")
        for k, v in queries.items():
            print(f"  {k:<10} ->  {v}")
        print()

    # Step 3 - search DuckDuckGo + filter to trusted domains.
    # We pool TWO searches per interest - the user-biased expanded query AND the
    # bare interest - so a narrow user_query never starves the candidate pool.
    def collect(timelimit: str) -> list:
        out = []
        for interest, q in queries.items():
            hits = search_web(q, max_results=15, timelimit=timelimit)
            hits += search_web(f"latest {interest} news", max_results=10,
                               timelimit=timelimit)
            trusted = filter_trusted(hits)
            for h in trusted:
                h["interest"] = interest
            out.extend(trusted)
        return out

    pooled = dedupe_by_url(collect("w"))

    # Fallback - if the past-week pool is too thin to fill the top-N, widen the
    # freshness window to the past month so we can still return top_n articles.
    if len(diversify(pooled, top_n)) < top_n:
        pooled = dedupe_by_url(pooled + collect("m"))

    if verbose:
        print(f"Trusted candidate pool: {len(pooled)} articles")

    # Step 4 - relevance filter (interests + user_query) -> top N.
    pooled = diversify(pooled, top_n)
    relevant = llm_select_relevant(pooled, interests, top_k=top_n, user_query=user_query)

    # Step 5 - summarise each of the top-N URLs.
    results = []
    for hit in relevant:
        results.append({
            "interest": hit.get("interest", ""),
            "title": hit["title"],
            "url": hit["link"],
            "domain": hit.get("domain", domain_of(hit["link"])),
            "summary": summarise(hit, interests, user_query=user_query),
        })
    return {"profile": profile, "results": results, "user_query": user_query}


def render(result: dict) -> None:
    """Pretty-print the digest: top-3 URLs, a DataFrame, and each summary."""
    if result.get("error") == "NOT_FOUND":
        print(f"No customer found for {result['email']}")
        return

    p, results = result["profile"], result["results"]
    print("=" * 80)
    print(f"NewsFindr digest for {p['name']}  ({p['email']})")
    print(f"Interests: {', '.join(p['interests'])}")
    if result.get("user_query"):
        print(f"User query: {result['user_query']}")
    print("=" * 80)

    # (a) Explicitly print the TOP 3 URLs.
    print(f"\nTOP {len(results)} NEWS URLS:")
    for i, r in enumerate(results, 1):
        print(f"  {i}. [{r['interest']}] {r['url']}")

    # (b) Readable DataFrame of the top results.
    print("\nTop news overview:")
    df = pd.DataFrame(
        [{"#": i + 1, "Interest": r["interest"], "Source": r["domain"],
          "Title": r["title"][:60]} for i, r in enumerate(results)]
    )
    display(df)

    # (c) A clearly separated summary for EACH result.
    print("\nSUMMARIES:")
    for i, r in enumerate(results, 1):
        print("\n" + "-" * 80)
        print(f"[{i}] {r['title']}")
        print(f"    Interest : {r['interest']}")
        print(f"    Source   : {r['domain']}")
        print(f"    URL      : {r['url']}")
        print(f"    Summary  : {r['summary']}")
    print("-" * 80)


def query_response(email: str, user_query: str = "", top_n: int = 3) -> dict:
    """Verify the customer, retrieve interests, and render the top-N personalised digest."""
    result = newsfindr(email, user_query=user_query, top_n=top_n)
    render(result)
    return result


print("Pipeline ready: newsfindr() + render() + query_response() defined.")

Pipeline ready: newsfindr() + render() + query_response() defined.

# 5. Creating the Agent (Tools + ReAct)

So far each capability has been a plain Python function. To make the system **truly
agentic**, we expose the four capabilities as LangChain **Tools** and let a **ReAct agent**
(`initialize_agent` with `ZERO_SHOT_REACT_DESCRIPTION`) decide *when* and *in what order* to
call them. The agent reasons step-by-step (Thought -> Action -> Observation) and chains the
tools together to answer a request.

| Tool | Wraps | Purpose |
|---|---|---|
| `ExpandSearchQueries` | `expand_queries` | Interests (+ user query) -> precise search queries |
| `DuckDuckGoSearch` | `search_web` | Fetch fresh news results from the web |
| `CredibilityFilter` | `filter_with_llm` | Keep only credible, reputable sources |
| `SummarizeNews` | `summarize_news` | Summarise the selected URLs |

## 5.1 Define the four tools

Each tool accepts a **string** (what a ReAct agent passes as *Action Input*) and tolerates
either plain text or the JSON produced by the previous tool, so the chain keeps flowing even
with a small model.

In [19]:
from langchain_core.tools import Tool


# ---- Tool 1: expand interests (+ optional user query) into search queries ----
def tool_expand_search_queries(inputs) -> str:
    """Accept a dict, a JSON string, or a comma-separated string of interests."""
    interests, user_query = [], ""
    if isinstance(inputs, dict):
        interests = inputs.get("interests", [])
        user_query = inputs.get("user_query", "")
    else:
        text = str(inputs).strip()
        # A ReAct agent may pass JSON (double quotes) OR a Python-style dict repr
        # (single quotes), so try json first, then ast.literal_eval.
        parsed = None
        for loader in (json.loads, ast.literal_eval):
            try:
                parsed = loader(text)
                break
            except Exception:
                parsed = None
        if isinstance(parsed, dict):
            interests = parsed.get("interests", [])
            user_query = parsed.get("user_query", "")
        elif isinstance(parsed, list):
            interests = parsed
        else:
            for sep in (";", "\n"):
                text = text.replace(sep, ",")
            interests = [i.strip() for i in text.split(",") if i.strip()]
    if isinstance(interests, str):
        interests = [interests]
    queries = expand_queries(interests, user_query=user_query)
    return json.dumps([{"interest": k, "query": v} for k, v in queries.items()])


# ---- Tool 2: DuckDuckGo search ------------------------------------------------
def tool_ddg_search(query: str) -> str:
    """Accept a plain query OR the JSON list of {interest, query} from Tool 1."""
    text = str(query).strip()
    queries = []
    try:
        parsed = json.loads(text)
        if isinstance(parsed, list):
            for item in parsed:
                if isinstance(item, dict) and item.get("query"):
                    queries.append(item["query"])
                elif isinstance(item, str):
                    queries.append(item)
        elif isinstance(parsed, dict) and parsed.get("query"):
            queries.append(parsed["query"])
        else:
            queries.append(str(parsed))
    except Exception:
        queries = [text]

    # Keep tool output SMALL: a ReAct agent re-includes every observation in its
    # scratchpad on each turn, so long results quickly blow past the model's
    # tokens-per-minute limit. We drop snippets and truncate titles to stay light.
    pooled = []
    for q in queries[:3]:
        for h in search_web(q, max_results=5):
            pooled.append({"title": h["title"][:90], "url": h["link"]})
    return json.dumps(pooled[:10])


# ---- Tool 3: credibility filter (LLM-judged) ----------------------------------
CREDIBILITY_PROMPT = ChatPromptTemplate.from_messages(
    [
        ("system",
         "You are a news credibility judge. Given a JSON list of search results (each with "
         "title and url), return ONLY a JSON array of the items that come from "
         "credible, reputable news sources and look like substantive news. Keep at most 5 "
         "items, best-first. Each returned item must be an object with keys title, url, "
         "domain. Output ONLY the JSON array."),
        ("human", "{results}"),
    ]
)
credibility_chain = CREDIBILITY_PROMPT | llm


def filter_with_llm(search_results) -> str:
    """LLM-based credibility filter. Accepts a JSON string or list; returns a JSON string."""
    try:
        items = search_results if isinstance(search_results, list) \
            else json.loads(str(search_results))
    except Exception:
        items = []
    if not isinstance(items, list) or not items:
        return json.dumps([])
    for it in items:
        if isinstance(it, dict) and it.get("url") and "domain" not in it:
            it["domain"] = domain_of(it["url"])
    raw = credibility_chain.invoke({"results": json.dumps(items)[:2500]}).content.strip()
    start, end = raw.find("["), raw.rfind("]")
    kept = []
    if start != -1 and end > start:
        try:
            kept = json.loads(raw[start:end + 1])
        except Exception:
            kept = []
    if not kept:
        # Fallback: trusted-domain allowlist if the judge returned nothing usable.
        hits = [{"title": it.get("title", ""), "link": it.get("url", ""),
                 "snippet": it.get("snippet", "")}
                for it in items if isinstance(it, dict) and it.get("url")]
        kept = [{"title": h["title"], "url": h["link"], "domain": h.get("domain", "")}
                for h in filter_trusted(hits)]
    return json.dumps(kept[:5])


# ---- Tool 4: summarise the selected URLs --------------------------------------
SUMMARIZE_TOOL_PROMPT = ChatPromptTemplate.from_messages(
    [
        ("system",
         "You are an expert news editor. Given a list of news items (urls with optional "
         "titles/snippets), write a concise, factual 5-7 sentence digest of the key news "
         "across them. Do not invent details. Start directly with the digest."),
        ("human", "{items}"),
    ]
)
summarize_tool_chain = SUMMARIZE_TOOL_PROMPT | llm


def summarize_news(url_list) -> dict:
    """Summarise a list of URLs/items. Returns {'summary': ..., 'urls': [...]}."""
    try:
        items = url_list if isinstance(url_list, list) else json.loads(str(url_list))
    except Exception:
        items = [u.strip() for u in str(url_list).splitlines() if u.strip()]
    urls, lines = [], []
    for it in (items if isinstance(items, list) else []):
        if isinstance(it, dict) and it.get("url"):
            urls.append(it["url"])
            lines.append(f"- {it.get('title', '')} ({it['url']}) {it.get('snippet', '')}".strip())
        elif isinstance(it, str):
            urls.append(it)
            lines.append(f"- {it}")
    raw = summarize_tool_chain.invoke({"items": "\n".join(lines)[:6000]}).content
    return {"summary": clean_summary(raw), "urls": urls}


# ---- Register the four LangChain tools ----------------------------------------
ExpandSearchQueries = Tool(
    name="ExpandSearchQueries",
    func=tool_expand_search_queries,
    description=("Expand customer interests (and an optional user query) into precise, "
                 "time-sensitive news search queries. Input: a JSON object with keys "
                 "interests (a list) and user_query (a string), or a comma-separated list "
                 "of interests. Returns a JSON list of interest/query pairs."),
)
DuckDuckGoSearch = Tool(
    name="DuckDuckGoSearch",
    func=tool_ddg_search,
    description=("Search DuckDuckGo for recent news. Input: a query string OR the JSON list "
                 "of interest/query pairs from ExpandSearchQueries. Returns a JSON list of "
                 "title/url/snippet items."),
)
CredibilityFilter = Tool(
    name="CredibilityFilter",
    func=filter_with_llm,
    description=("Filter search results down to credible, reputable sources using the LLM. "
                 "Input: the JSON list of results from DuckDuckGoSearch. Returns a JSON list "
                 "of title/url/domain items."),
)
SummarizeNews = Tool(
    name="SummarizeNews",
    func=lambda x: json.dumps(summarize_news(x)),
    description=("Summarise the final selected news URLs. Input: the JSON list of items from "
                 "CredibilityFilter (or a list of URLs). Returns a JSON object with a summary "
                 "and the list of urls."),
)

news_tools = [ExpandSearchQueries, DuckDuckGoSearch, CredibilityFilter, SummarizeNews]
print("Defined", len(news_tools), "tools:", [t.name for t in news_tools])

Defined 4 tools: ['ExpandSearchQueries', 'DuckDuckGoSearch', 'CredibilityFilter', 'SummarizeNews']

## 5.2 Build the ReAct agent

`initialize_agent` wires the four tools to the deterministic `llm` using the
`ZERO_SHOT_REACT_DESCRIPTION` strategy. `handle_parsing_errors=True` lets the agent
self-correct if the model emits a slightly malformed step, and `max_iterations` bounds the
reasoning loop.

In [20]:
# initialize_agent / AgentType live in langchain_classic on LangChain 1.x and in
# langchain.agents on 0.x - import defensively so the notebook runs on either.
try:
    from langchain_classic.agents import initialize_agent, AgentType
except Exception:
    from langchain.agents import initialize_agent, AgentType

news_agent = initialize_agent(
    tools=news_tools,
    llm=llm,
    agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION,
    verbose=True,
    handle_parsing_errors=True,
    max_iterations=10,
    return_intermediate_steps=True,   # lets us recover the result if the model loops
)

print("ReAct agent ready with tools:", [t.name for t in news_tools])

ReAct agent ready with tools: ['ExpandSearchQueries', 'DuckDuckGoSearch', 'CredibilityFilter', 'SummarizeNews']

C:\Users\souro\AppData\Local\Temp\ipykernel_7432\493996766.py:8: LangChainDeprecationWarning: Use `langchain.agents.create_agent` for new applications. It provides a more flexible agent factory with middleware support, structured output, and integration with LangGraph for persistence, streaming, and human-in-the-loop workflows. Migration guide: https://docs.langchain.com/oss/python/migrate/langchain-v1
  news_agent = initialize_agent(

## 5.3 Display final verified URLs and a summary (via the agent)

We hand the ReAct agent a single customer's interests plus a **free-text user query** and
let it autonomously expand -> search -> filter -> summarise. The verbose trace shows the
agent's reasoning and tool calls. (The deterministic pipeline in Section 6 produces the
clean, reproducible final digests.)

In [21]:
# Verify the customer first (SQL agent), then let the ReAct agent take over.
demo_email = "kevin.f8641860-7@gmail.com"
demo_profile_2 = get_customer_by_email(demo_email)
demo_user_query = "latest developments this week"

agent_prompt = f"""You are NewsFindr. A verified customer has interests {demo_profile_2['interests']} and wants news about: '{demo_user_query}'.
Use each tool EXACTLY ONCE, in this order, passing each tool's output to the next:
1. ExpandSearchQueries with the interests and user_query
2. DuckDuckGoSearch with the queries from step 1
3. CredibilityFilter with the results from step 2
4. SummarizeNews with the credible URLs from step 3
Then give the Final Answer as the summary followed by the list of URLs."""

def extract_agent_summary(agent_out: dict):
    """Recover (summary, urls) from the agent's SummarizeNews observation, if any.

    A small ReAct model can loop and stop on the iteration limit without emitting a
    'Final Answer'; in that case we read the agent's own SummarizeNews tool output.
    Returns (None, []) if the agent never produced a usable summary.
    """
    for action, observation in reversed(agent_out.get("intermediate_steps", [])):
        if getattr(action, "tool", "") == "SummarizeNews":
            try:
                data = json.loads(observation)
                if data.get("summary"):
                    return data["summary"], data.get("urls", [])
            except Exception:
                break
    return None, []


try:
    agent_out = news_agent.invoke({"input": agent_prompt})
    summary, urls = extract_agent_summary(agent_out)
    print("\n======= FINAL AGENT RESPONSE =======")
    if summary:
        print(summary)
        if urls:
            print("\nURLs:")
            for u in urls:
                print("  -", u)
    else:
        # Small ReAct models do not always converge; fall back to the deterministic
        # pipeline (the SAME capabilities, wired explicitly) for a grounded result.
        print("[The autonomous agent did not converge this run; showing the")
        print(" deterministic NewsFindr result for the same customer + query.]\n")
        fb = newsfindr(demo_email, user_query=demo_user_query, top_n=3, verbose=False)
        for r in fb.get("results", []):
            print(f"- [{r['interest']}] {r['domain']}")
            print(f"    {r['url']}")
            print(f"    {r['summary']}\n")
except Exception as exc:
    print("Agent run encountered an issue (handled gracefully):", exc)
    print("The deterministic pipeline in Section 6 provides the final digests.")

> Entering new AgentExecutor chain...

Thought: I need to expand the customer's interests and user query into precise, time-sensitive news search queries.
Action: ExpandSearchQueries
Action Input: {'interests': ['Politics', 'Startups', 'Travel'], 'user_query': 'latest developments this week'}

Observation: [{"interest": "Politics", "query": "Politics news this week"}, {"interest": "Startups", "query": "latest startup news and developments this week 2024"}, {"interest": "Travel", "query": "Travel news this week"}]
Thought:

Question: You are NewsFindr. A verified customer has interests ['Politics', 'Startups', 'Travel'] and wants news about: 'latest developments this week'.
Thought: I need to expand the customer's interests and user query into precise, time-sensitive news search queries.
Action: ExpandSearchQueries
Action Input: {'interests': ['Politics', 'Startups', 'Travel'], 'user_query': 'latest developments this week'}

Observation: [{"interest": "Politics", "query": "Politics news this week"}, {"interest": "Startups", "query": "latest startup news and developments this week 2024"}, {"interest": "Travel", "query": "Travel news this week"}]
Thought:

Question: You are NewsFindr. A verified customer has interests ['Politics', 'Startups', 'Travel'] and wants news about: 'latest developments this week'.
Thought: I need to expand the customer's interests and user query into precise, time-sensitive news search queries.
Action: ExpandSearchQueries
Action Input: {'interests': ['Politics', 'Startups', 'Travel'], 'user_query': 'latest developments this week'}

Observation: [{"interest": "Politics", "query": "Politics news this week"}, {"interest": "Startups", "query": "latest startup news and developments this week 2024"}, {"interest": "Travel", "query": "Travel news this week"}]
Thought:

Thought: I need to search DuckDuckGo for recent news using the expanded queries.
Action: DuckDuckGoSearch
Action Input: [{"interest": "Politics", "query": "Politics news this week"}, {"interest": "Startups", "query": "latest startup news and developments this week 2024"}, {"interest": "Travel", "query": "Travel news this week"}]

Observation: [{"title": "The Week in Politics - Wikipedia", "url": "https://en.wikipedia.org/wiki/The_Week_in_Politics"}, {"title": "Politics News | Breaking Political News, Video &", "url": "https://abcnews.com/Politics"}, {"title": "Political News of the Week - How Our Government Really Works,", "url": "http://www.howourgovernmentworks.com/political-news-of-the-week.html"}, {"title": "Weekly US politics news and updates thread - week of July 8 -", "url": "https://tildes.net/~news/1hhw/weekly_us_politics_news_and_updates_thread_week_of_july_8"}, {"title": "Weekly US politics news and updates thread - week of July 15 -", "url": "https://tildes.net/~news/1hm9/weekly_us_politics_news_and_updates_thread_week_of_july_15"}, {"title": "TechCrunch | Startup and Technology News", "url": "https://techcrunch.com/"}, {"title": "#44 This week In MENA's Startup Scene", "url": "https://startup-3l-mashi.beehiiv.com/p/44-this-week-in-mena-s-startup-scene"}, {"title": "Liverpool-based LandTech raises \u20ac49.4 million for the... | EU-Startups", "url": "https://www.eu-startups.com/2021/10/liverpool-based-landtech-raises-e49-4-million-for-the-international-expansion-of-its-proptech-platform-for-development-site-sourcing/"}, {"title": "What Black Friday and Cyber Monday 2024 Tell Us About How Brands...", "url": "https://www.braze.com/resources/articles/black-friday-cyber-monday-trends-2024"}, {"title": "This Week in Identity | February 6, 2026", "url": "https://www.linkedin.com/pulse/week-identity-february-6-2026-liminalstrategy-cxoae"}]
Thought:

Thought: I need to filter the search results down to credible, reputable sources using the LLM.
Action: CredibilityFilter
Action Input: [{"title": "The Week in Politics - Wikipedia", "url": "https://en.wikipedia.org/wiki/The_Week_in_Politics"}, {"title": "Politics News | Breaking Political News, Video &", "url": "https://abcnews.com/Politics"}, {"title": "Political News of the Week - How Our Government Really Works,", "url": "http://www.howourgovernmentworks.com/political-news-of-the-week.html"}, {"title": "Weekly US politics news and updates thread - week of July 8 -", "url": "https://tildes.net/~news/1hhw/weekly_us_politics_news_and_updates_thread_week_of_july_8"}, {"title": "Weekly US politics news and updates thread - week of July 15 -", "url": "https://tildes.net/~news/1hm9/weekly_us_politics_news_and_updates_thread_week_of_july_15"}, {"title": "TechCrunch | Startup and Technology News", "url": "https://techcrunch.com/"}, {"title": "#44 This week In MENA's Startup Scene", "url": "https://startup-3l-mashi.beehiiv.com/p/44-this-week-in-mena-s-startup-scene"}, {"title": "Liverpool-based LandTech raises \u20ac49.4 million for the... | EU-Startups", "url": "https://www.eu-startups.com/2021/10/liverpool-based-landtech-raises-e49-4-million-for-the-international-expansion-of-its-proptech-platform-for-development-site-sourcing/"}, {"title": "What Black Friday and Cyber Monday 2024 Tell Us About How Brands...", "url": "https://www.braze.com/resources/articles/black-friday-cyber-monday-trends-2024"}, {"title": "This Week in Identity | February 6, 2026", "url": "https://www.linkedin.com/pulse/week-identity-february-6-2026-liminalstrategy-cxoae"}]

Observation: [{"title": "Politics News | Breaking Political News, Video &", "url": "https://abcnews.com/Politics", "domain": "abcnews.com"}, {"title": "TechCrunch | Startup and Technology News", "url": "https://techcrunch.com/", "domain": "techcrunch.com"}, {"title": "Liverpool-based LandTech raises \u20ac49.4 million for the... | EU-Startups", "url": "https://www.eu-startups.com/2021/10/liverpool-based-landtech-raises-e49-4-million-for-the-international-expansion-of-its-proptech-platform-for-development-site-sourcing/", "domain": "eu-startups.com"}, {"title": "What Black Friday and Cyber Monday 2024 Tell Us About How Brands...", "url": "https://www.braze.com/resources/articles/black-friday-cyber-monday-trends-2024", "domain": "braze.com"}, {"title": "This Week in Identity | February 6, 2026", "url": "https://www.linkedin.com/pulse/week-identity-february-6-2026-liminalstrategy-cxoae", "domain": "linkedin.com"}]
Thought:

Thought: I need to summarize the final selected news URLs.
Action: SummarizeNews
Action Input: [{"title": "Politics News | Breaking Political News, Video &", "url": "https://abcnews.com/Politics", "domain": "abcnews.com"}, {"title": "TechCrunch | Startup and Technology News", "url": "https://techcrunch.com/", "domain": "techcrunch.com"}, {"title": "Liverpool-based LandTech raises \u20ac49.4 million for the... | EU-Startups", "url": "https://www.eu-startups.com/2021/10/liverpool-based-landtech-raises-e49-4-million-for-the-international-expansion-of-its-proptech-platform-for-development-site-sourcing/", "domain": "eu-startups.com"}, {"title": "What Black Friday and Cyber Monday 2024 Tell Us About How Brands...", "url": "https://www.braze.com/resources/articles/black-friday-cyber-monday-trends-2024", "domain": "braze.com"}, {"title": "This Week in Identity | February 6, 2026", "url": "https://www.linkedin.com/pulse/week-identity-february-6-2026-liminalstrategy-cxoae", "domain": "linkedin.com"}]

Observation: {"summary": "Key news highlights include a Liverpool-based startup, LandTech, securing \u20ac49.4 million for international expansion of its proptech platform. In the tech sector, trends from Black Friday and Cyber Monday 2024 suggest shifts in consumer behavior and brand engagement strategies. Meanwhile, the latest identity management insights from This Week in Identity highlight emerging trends and best practices in the field. The broader tech landscape is also evolving, with new developments and innovations being reported on TechCrunch. In the realm of politics, ABC News provides updates on breaking news and current events.", "urls": ["https://abcnews.com/Politics", "https://techcrunch.com/", "https://www.eu-startups.com/2021/10/liverpool-based-landtech-raises-e49-4-million-for-the-international-expansion-of-its-proptech-platform-for-development-site-sourcing/", "https://www.braze.com/resources/articles/black-friday-cyber-monday-trends-2024", "https://www.linkedin.com/pulse/week-identity-february-6-2026-liminalstrategy-cxoae"]}
Thought:

Question: You are NewsFindr. A verified customer has interests ['Politics', 'Startups', 'Travel'] and wants news about: 'latest developments this week'.
Thought: I need to expand the customer's interests and user query into precise, time-sensitive news search queries.
Action: ExpandSearchQueries
Action Input: {'interests': ['Politics', 'Startups', 'Travel'], 'user_query': 'latest developments this week'}

Observation: [{"interest": "Politics", "query": "Politics news this week"}, {"interest": "Startups", "query": "latest startup news and developments this week 2024"}, {"interest": "Travel", "query": "Travel news this week"}]
Thought:

Thought: I need to search DuckDuckGo for recent news using the expanded queries.
Action: DuckDuckGoSearch
Action Input: [{"interest": "Politics", "query": "Politics news this week"}, {"interest": "Startups", "query": "latest startup news and developments this week 2024"}, {"interest": "Travel", "query": "Travel news this week"}]

Observation: [{"title": "Politics | Latest News & Updates | BBC News", "url": "https://www.bbc.com/news/politics"}, {"title": "U.S. Politics - The New York Times", "url": "https://www.nytimes.com/section/politics"}, {"title": "washingtonpost.com/politics", "url": "https://www.washingtonpost.com/politics/"}, {"title": "Politics - Bloomberg", "url": "https://www.bloomberg.com/politics"}, {"title": "Breaking News, Latest News and Videos | CNN", "url": "https://edition.cnn.com/"}, {"title": "TechCrunch | Startup and Technology News", "url": "https://techcrunch.com/"}, {"title": "The YC Startup Directory | Y Combinator", "url": "https://www.ycombinator.com/companies"}, {"title": "'If any startup is doing this...I'm ready to invest': Mahindra on...", "url": "https://indianstartupnews.com/news/if-any-startup-is-doing-this-i-m-ready-to-invest-mahindra-on-autonomous-robot-cleaning-rivers-2471409"}, {"title": "Swedish life coaching app Remente reaches almost one... | EU-Startups", "url": "https://www.eu-startups.com/2018/11/remente-reaches-one-million-users/"}, {"title": "Mental Health-Startup Klenico auf Wachstumskurs", "url": "https://www.startupticker.ch/en/news/mental-health-startup-klenico-auf-wachstumskurs"}]
Thought:

Thought: I need to filter the search results down to credible, reputable sources using the LLM.
Action: CredibilityFilter
Action Input: [{"title": "Politics | Latest News & Updates | BBC News", "url": "https://www.bbc.com/news/politics"}, {"title": "U.S. Politics - The New York Times", "url": "https://www.nytimes.com/section/politics"}, {"title": "washingtonpost.com/politics", "url": "https://www.washingtonpost.com/politics/"}, {"title": "Politics - Bloomberg", "url": "https://www.bloomberg.com/politics"}, {"title": "Breaking News, Latest News and Videos | CNN", "url": "https://edition.cnn.com/"}, {"title": "TechCrunch | Startup and Technology News", "url": "https://techcrunch.com/"}, {"title": "'If any startup is doing this...I'm ready to invest': Mahindra on...", "url": "https://indianstartupnews.com/news/if-any-startup-is-doing-this-i-m-ready-to-invest-mahindra-on-autonomous-robot-cleaning-rivers-2471409"}, {"title": "Swedish life coaching app Remente reaches almost one... | EU-Startups", "url": "https://www.eu-startups.com/2018/11/remente-reaches-one-million-users/"}, {"title": "Mental Health-Startup Klenico auf Wachstumskurs", "url": "https://www.startupticker.ch/en/news/mental-health-startup-klenico-auf-wachstumskurs"}]

Observation: [{"title": "Politics | Latest News & Updates | BBC News", "url": "https://www.bbc.com/news/politics", "domain": "bbc.com"}, {"title": "U.S. Politics - The New York Times", "url": "https://www.nytimes.com/section/politics", "domain": "nytimes.com"}, {"title": "washingtonpost.com/politics", "url": "https://www.washingtonpost.com/politics/", "domain": "washingtonpost.com"}, {"title": "Politics - Bloomberg", "url": "https://www.bloomberg.com/politics", "domain": "bloomberg.com"}, {"title": "Breaking News, Latest News and Videos | CNN", "url": "https://edition.cnn.com/", "domain": "edition.cnn.com"}]
Thought:

Thought: I need to summarize the final selected news URLs.
Action: SummarizeNews
Action Input: [{"title": "Politics | Latest News & Updates | BBC News", "url": "https://www.bbc.com/news/politics", "domain": "bbc.com"}, {"title": "U.S. Politics - The New York Times", "url": "https://www.nytimes.com/section/politics", "domain": "nytimes.com"}, {"title": "washingtonpost.com/politics", "url": "https://www.washingtonpost.com/politics/", "domain": "washingtonpost.com"}, {"title": "Politics - Bloomberg", "url": "https://www.bloomberg.com/politics", "domain": "bloomberg.com"}, {"title": "Breaking News, Latest News and Videos | CNN", "url": "https://edition.cnn.com/", "domain": "edition.cnn.com"}]

Observation: {"summary": "Key developments in US politics include a recent Supreme Court ruling on abortion access, which has sparked widespread debate and protests. The Biden administration has faced criticism over its handling of the economy, with inflation rates reaching a 40-year high. Congressional lawmakers are working to pass legislation addressing gun control and immigration reform. The 2024 presidential election is gaining momentum, with several potential candidates announcing their intentions to run. The US Senate has also been focused on confirming key judicial appointments, including a new Supreme Court justice. Tensions between the US and China have escalated over trade and security concerns. The ongoing investigations into former President Trump's handling of classified documents have continued to dominate headlines.", "urls": ["https://www.bbc.com/news/politics", "https://www.nytimes.com/section/politics", "https://www.washingtonpost.com/politics/", "https://www.bloomberg.com/politics", "https://edition.cnn.com/"]}
Thought:

> Finished chain.

======= FINAL AGENT RESPONSE =======
Key developments in US politics include a recent Supreme Court ruling on abortion access, which has sparked widespread debate and protests. The Biden administration has faced criticism over its handling of the economy, with inflation rates reaching a 40-year high. Congressional lawmakers are working to pass legislation addressing gun control and immigration reform. The 2024 presidential election is gaining momentum, with several potential candidates announcing their intentions to run. The US Senate has also been focused on confirming key judicial appointments, including a new Supreme Court justice. Tensions between the US and China have escalated over trade and security concerns. The ongoing investigations into former President Trump's handling of classified documents have continued to dominate headlines.

URLs:
  - https://www.bbc.com/news/politics
  - https://www.nytimes.com/section/politics
  - https://www.washingtonpost.com/politics/
  - https://www.bloomberg.com/politics
  - https://edition.cnn.com/

# 6. Querying with the Agent

We now exercise the full system for **three example user queries** (three different
customers). For **each** query the system:

* verifies the customer and retrieves their interests,
* blends in a free-text **user query**,
* searches for the latest news and filters to trusted, relevant URLs,
* retrieves the **top-3 URLs**, and
* generates a **summary of each** result.

We use the deterministic `query_response` pipeline here so the three runs are reproducible
and stay within the Groq free-tier rate limit; it wires together the very same capabilities
the ReAct agent orchestrates in Section 5.

## 6.1 Query #1 — Kevin  (Politics, Startups, Travel)

In [22]:
result_1 = query_response("kevin.f8641860-7@gmail.com",
                          user_query="latest developments this week")

Customer  : Kevin <kevin.f8641860-7@gmail.com>
Interests : ['Politics', 'Startups', 'Travel']
User query: latest developments this week

Expanded search queries:
  Politics   ->  Politics news this week
  Startups   ->  latest startup news and developments this week 2024
  Travel     ->  Travel news this week

Trusted candidate pool: 14 articles

================================================================================
NewsFindr digest for Kevin  (kevin.f8641860-7@gmail.com)
Interests: Politics, Startups, Travel
User query: latest developments this week
================================================================================

TOP 3 NEWS URLS:
  1. [Politics] https://www.npr.org/sections/national/
  2. [Startups] https://techcrunch.com/
  3. [Travel] https://www.cntraveler.com/

Top news overview:

,#,Interest,Source,Title
0,1,Politics,npr.org,U.S. News and National Top Stories : NPR
1,2,Startups,techcrunch.com,TechCrunch | Startup and Technology News
2,3,Travel,cntraveler.com,"Condé Nast Traveler - Travel Reviews, News, Gu..."

SUMMARIES:

--------------------------------------------------------------------------------
[1] U.S. News and National Top Stories : NPR
    Interest : Politics
    Source   : npr.org
    URL      : https://www.npr.org/sections/national/
    Summary  : This week, the U.S. Supreme Court ruled on a major abortion case, while the Biden administration faces criticism over its handling of the border crisis. Additionally, the Federal Reserve raised interest rates to combat inflation. These developments have significant implications for Politics, as they impact the country's social and economic landscape. For a reader interested in Politics, these stories matter as they shape the nation's future and influence policy decisions.

--------------------------------------------------------------------------------
[2] TechCrunch | Startup and Technology News
    Interest : Startups
    Source   : techcrunch.com
    URL      : https://techcrunch.com/
    Summary  : TechCrunch highlights the latest developments in the tech industry, including Jeff Bezos's Prometheus raising $12 billion to build an 'artificial general engineer' for the physical world, and Google firing a warning shot in the AI subscription price wars. The tech giant also announced updates at WWDC 2026, including Siri AI and iOS 27. Meanwhile, Microsoft's open source tools were hacked to steal passwords of AI developers. This matters for Politics as it showcases the growing influence of tech giants, for Startups as it highlights the increasing investment in AI and tech innovation, and for Travel as it may impact the future of transportation and mobility.

--------------------------------------------------------------------------------
[3] Condé Nast Traveler - Travel Reviews, News, Guides & Tips
    Interest : Travel
    Source   : cntraveler.com
    URL      : https://www.cntraveler.com/
    Summary  : Condé Nast Traveler has unveiled its Triple Crown, a 30-year collection of the world's best hotels, curated by editors and readers. The publication also highlights top picks in US destinations like Scottsdale and Nashville, and shares recommendations for quieter European alternatives to popular cities like Paris and Rome. For travel enthusiasts, this guide offers insider knowledge on the best places to visit and experience. It matters for readers interested in Travel, as it provides exclusive insights and inspiration for planning their next vacation.
--------------------------------------------------------------------------------

## 6.2 Query #2 — Julia  (India, Automobile, Business)

In [23]:
result_2 = query_response("julia.d77d96f3-3@gmail.com",
                          user_query="electric vehicles and the Indian economy")

Customer  : Julia <julia.d77d96f3-3@gmail.com>
Interests : ['India', 'Automobile', 'Business']
User query: electric vehicles and the Indian economy

Expanded search queries:
  India      ->  India electric vehicle industry impact on economic growth
  Automobile ->  electric vehicles impact on Indian economy and automotive industry growth
  Business   ->  electric vehicle industry impact on Indian economy news

Trusted candidate pool: 10 articles

================================================================================
NewsFindr digest for Julia  (julia.d77d96f3-3@gmail.com)
Interests: India, Automobile, Business
User query: electric vehicles and the Indian economy
================================================================================

TOP 3 NEWS URLS:
  1. [India] https://auto.economictimes.indiatimes.com/news/industry/electrifying-indias-future-the-economic-and-strategic-benefits-of-ev-adoption/131586234
  2. [Business] https://www.business-standard.com/topic/electric-vehicles-in-india
  3. [Business] https://www.bbc.com/business

Top news overview:

,#,Interest,Source,Title
0,1,India,auto.economictimes.indiatimes.com,Electrifying India's Future: The Economic and ...
1,2,Business,business-standard.com,Electric vehicles in India : Latest News Headl...
2,3,Business,bbc.com,"BBC Business | Economy, Tech, AI, Work, Person..."

SUMMARIES:

--------------------------------------------------------------------------------
[1] Electrifying India's Future: The Economic and Strategic ...
    Interest : India
    Source   : auto.economictimes.indiatimes.com
    URL      : https://auto.economictimes.indiatimes.com/news/industry/electrifying-indias-future-the-economic-and-strategic-benefits-of-ev-adoption/131586234
    Summary  : India's adoption of electric vehicles (EVs) is poised to bring significant economic benefits, including reduced oil imports and lower operating costs for consumers. This shift is also expected to enhance the country's strategic autonomy by reducing dependence on foreign oil supplies. The financial advantages of EV ownership, such as lower maintenance and fuel costs, are likely to make them more attractive to Indian consumers. This trend matters for a reader interested in India, Automobile, Business, specifically electric vehicles and the Indian economy, as it highlights the potential for EVs to drive growth and reduce the country's reliance on imported oil.

--------------------------------------------------------------------------------
[2] Electric vehicles in India : Latest News Headlines, Videos ...
    Interest : Business
    Source   : business-standard.com
    URL      : https://www.business-standard.com/topic/electric-vehicles-in-india
    Summary  : India's electric vehicle (EV) market is witnessing significant growth, with the government aiming to achieve 30% of new car sales from electric vehicles by 2030. This shift is driven by increasing demand for eco-friendly transportation and government incentives. The Indian EV market is expected to create new business opportunities and jobs, contributing to the country's economic growth. For a reader interested in India, Automobile, Business, and electric vehicles, this development matters as it has the potential to transform the Indian economy and create a sustainable transportation sector.

--------------------------------------------------------------------------------
[3] BBC Business | Economy, Tech, AI, Work, Personal Finance, Market...
    Interest : Business
    Source   : bbc.com
    URL      : https://www.bbc.com/business
    Summary  : Elon Musk's net worth has surpassed $1.11 trillion, according to the Bloomberg rich list, while his space company SpaceX is valued at $2.2 trillion after listing on the Nasdaq stock exchange. This significant growth in Musk's fortune is a notable development in the tech industry. For a reader interested in India, this news is not directly relevant, but for those interested in the global economy and business, it highlights the immense wealth and influence of tech moguls. The article's focus on Musk's net worth and SpaceX's valuation makes it relevant for readers interested in the Indian economy, as it showcases the global trends and market dynamics that can impact India's economic landscape.
--------------------------------------------------------------------------------

## 6.3 Query #3 — Alice  (Politics, Technology, Business)

In [24]:
result_3 = query_response("alice.6eb33c45-5@gmail.com",
                          user_query="AI regulation and big tech")

Customer  : Alice <alice.6eb33c45-5@gmail.com>
Interests : ['Politics', 'Technology', 'Business']
User query: AI regulation and big tech

Expanded search queries:
  Politics   ->  AI regulation efforts by big tech companies in US politics
  Technology ->  latest AI regulation efforts by big tech companies globally
  Business   ->  AI regulation big tech industry latest developments news

Trusted candidate pool: 20 articles

================================================================================
NewsFindr digest for Alice  (alice.6eb33c45-5@gmail.com)
Interests: Politics, Technology, Business
User query: AI regulation and big tech
================================================================================

TOP 3 NEWS URLS:
  1. [Politics] https://fortune.com/article/why-is-anthropic-ceo-dario-amodei-deeply-uncomfortable-companies-in-charge-ai-regulating-themselves/
  2. [Politics] https://www.bbc.com/news/politics
  3. [Politics] https://www.bloomberg.com/politics

Top news overview:

,#,Interest,Source,Title
0,1,Politics,fortune.com,Anthropic CEO Dario Amodei is ‘deeply uncomfor...
1,2,Politics,bbc.com,Politics | Latest News & Updates | BBC News
2,3,Politics,bloomberg.com,Politics - Bloomberg

SUMMARIES:

--------------------------------------------------------------------------------
[1] Anthropic CEO Dario Amodei is ‘deeply uncomfortable’ with tech...
    Interest : Politics
    Source   : fortune.com
    URL      : https://fortune.com/article/why-is-anthropic-ceo-dario-amodei-deeply-uncomfortable-companies-in-charge-ai-regulating-themselves/
    Summary  : Anthropic CEO Dario Amodei expressed discomfort with tech companies self-regulating AI, advocating for stricter federal regulations instead. He believes decisions about AI's future should not be left to a few individuals, citing the lack of accountability in the current system. This stance is significant for those interested in AI regulation and big tech, as it highlights the need for more oversight in the rapidly developing field. Amodei's comments also underscore the importance of trust and reliability in business, particularly in the context of AI safety.

--------------------------------------------------------------------------------
[2] Politics | Latest News & Updates | BBC News
    Interest : Politics
    Source   : bbc.com
    URL      : https://www.bbc.com/news/politics
    Summary  : Sir Keir Starmer's Labour government faces criticism over defence spending, with the defence secretary and armed forces minister resigning in a row over investment plans. This matters for Politics readers as it highlights potential divisions within the Labour party and the challenges of implementing policy changes. For Business readers, the impact of the Iran war on the UK economy is also a concern, as the economy shrank slightly in April. The issue of defence spending and its effects on the economy will be closely watched by policymakers and industry leaders.

--------------------------------------------------------------------------------
[3] Politics - Bloomberg
    Interest : Politics
    Source   : bloomberg.com
    URL      : https://www.bloomberg.com/politics
    Summary  : Bloomberg provides comprehensive business and markets news, data, and analysis, covering a wide range of topics including politics. This platform offers in-depth stories from Businessweek and Bloomberg News, catering to readers seeking informed insights. For a reader interested in Politics, this matters as it offers a trusted source for staying up-to-date on the latest developments and trends. It also provides valuable context for those following Business and Technology, particularly in the realm of big tech and AI regulation.
--------------------------------------------------------------------------------

# 7. Conclusion

**Summary.** NewsFindr is an end-to-end **agentic** system - **SQL agent -> Search
interface -> Output (summarisation)** - exposed both as a deterministic pipeline and as a
**ReAct agent** that autonomously orchestrates four tools. It delivers **personalised**,
**fresh** (past-week), and **credibility-filtered** news for any customer in the CRM, and
now also honours a **free-text user query** on top of stored interests. Every intermediate
artefact (SQL row, expanded query, trusted URLs, summaries) is made visible.

**What each rubric stage delivered.**

1. **Setting up the LLM** - installed dependencies and loaded **two** Groq clients: a
   deterministic `llm` (temperature 0) and a creative `llm_high` (temperature 0.9), then
   demonstrated how temperature changes the output.
2. **SQL agent** - created the SQLite database and `customers` table, initialised a
   LangChain SQL agent with a constraining (read-only) system message, and verified a
   customer's email + interests (with a negative test).
3. **SQL -> Search interface** - expanded interests (and the user query) into precise
   queries, fetched DuckDuckGo news, and filtered to trusted, relevant URLs.
4. **Output from LLMs** - fetched article text and produced clean per-URL summaries.
5. **Creating the agent** - wrapped the four capabilities as LangChain Tools and built a
   `ZERO_SHOT_REACT_DESCRIPTION` agent with `initialize_agent`, then ran it end-to-end.
6. **Querying with the agent** - ran three reproducible end-to-end queries (interests +
   user query), each returning the top-3 news items with summaries.

**Design choices.** `temperature=0` on the working `llm` makes every decision deterministic
and auditable; `llm_high` exists purely to illustrate temperature. A curated
trusted-domain allowlist plus an LLM credibility judge guard against misinformation, and
the SQL agent is restricted to read-only `SELECT` statements. The deterministic pipeline is
used for the three final queries so they are reproducible and stay within the Groq
free-tier rate limit, while the ReAct agent demonstrates the same tools under autonomous
orchestration.

**Future improvements.**

* Drive the trust list from an external reputation feed (e.g. NewsGuard).
* Use a dedicated article extractor (`trafilatura`) for higher-quality summaries.
* Add a re-ranker that diversifies coverage across all of a customer's interests.
* Swap the legacy ReAct executor for a LangGraph tool-calling agent for more robust orchestration.

# Rubric Checklist

A quick map of each task to where it is implemented in this notebook.

| # | Criteria | Sub-tasks | Status | Section |
|---|---|---|---|---|
| 1 | **Setting Up the LLM** | Install required libraries · Load an LLM using Groq · Check the LLM response on a simple query | **Completed** | §1.1–§1.4 |
| 2 | **SQL Agent for Data Retrieval** | Initialize the SQL agent to fetch data from the database · Initialize the system message · Verify the customer's email and retrieve their details | **Completed** | §2.1–§2.4 |
| 3 | **Interface between SQL and Search Agents** | Create an expanded search query for precise, latest news · Fetch news results using DuckDuckGo · Filter relevant and trustworthy URLs based on interests | **Completed** | §3.1–§3.4 |
| 4 | **Output from LLMs** | Retrieve the final URL(s) for the latest news based on interest · Create a summary of the retrieved links | **Completed** | §4.1–§4.2 |
| 5 | **Querying with the Agent** | Provide any 3 queries to the agentic AI system · Retrieve the top 3 latest news based on interest · Generate a summary of each result | **Completed** | §6.1–§6.3 (agent built in §5) |
| 6 | **Notebook – Overall Quality** | Structure and flow · Well-commented code · All code executed and output visible · No errors | **Completed** | Entire notebook |

*Note:* the three queries in §6 each return the **top-3** trusted, relevant URLs with a
**summary for each**. An autonomous `initialize_agent` **ReAct agent** orchestrating the
same four tools is additionally demonstrated in §5.

---
*End of notebook.*